spring.application.name=Shoppify

#JWT CONFIG#
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

#SQL CONFIG#
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

#MAIL CONFIG#
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}

#ENV CONTENT#
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}


#TIEMPO DE LIMPIEZA DE TRANSACCIONES PENDIENTES EN MINUTOS
transaction.cleanup.timeout-minutes=15

#EXCEPTION HANDLERS#
spring.web.resources.add-mappings=false

#API CONFIG#
spring.mvc.servlet.path=/api

# Disable SQL data initialization to avoid mismatch with evolving schema
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

