spring.application.name=Shoppify

#JWT CONFIG#
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

#SQL CONFIG#
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#MAIL CONFIG#
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}


#TIEMPO DE LIMPIEZA DE TRANSACCIONES PENDIENTES EN MINUTOS
transaction.cleanup.timeout-minutes=15

#EXCEPTION HANDLERS#
spring.web.resources.add-mappings=false

#API CONFIG#
server.port=${PORT:8080}
spring.mvc.servlet.path=/api

# Disable SQL data initialization to avoid mismatch with evolving schema
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
